<script>
import { Icon } from "ant-design-vue";
const AntIcon = Icon.createFromIconfontCN({
  scriptUrl: "//at.alicdn.com/t/font_1021869_ljx8usaq9hj.js" // generated by iconfont.cn
});

export default AntIcon;
</script>
